### ISSUE TITLE
Empty pop up on mouse over

### ISSUE THREAD

**Issue by kosteman** [sbtqa/tag-editor#18]
![Screenshot 2022-08-22 at 08 58 31](https://user-images.githubusercontent.com/10125178/185862131-0d162dbb-6de3-4dfc-b2da-ebc4639d5e26.png)

**Comment by clicman** [comment]
Not a regression, but I don't know how to fix it. Plugin code does nothing about this behaviour, its by default

**Comment by clicman** [comment]
Found a reason. elements with multiple annotations cannot have a pup-up. But disappointing empty popup caused by bug. I'll fix it

**Comment by kosteman** [comment]
fixed in 1.5.6
